sudo: required
language: elixir
elixir:
  - 1.11.2
otp_release:
  - 22.3.3

script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix coveralls.hmtl

after_success:
  - bash <(curl -s https://codecov.io/bash)
