sudo: required
language: elixir
elixir:
  - 1.12.2
otp_release:
  - 22.3.3

env:
  - MIX_ENV=test

script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
